version: '3'
services:
  top.api:
    image: docker.pkg.github.com/darksomev/nest-js-test-app/nest-js-test-app:latest
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env